* Emergence of formal geometry
** Geometric order
In order to achieve living structure, at a certain stage, it is necessary to 
seize hold of the building design and force it into an almost brutal, simple,
massive geometric mold

All living processes use unfolding to create geometric order.
When we contemplate any living process at all, we always see that the length and
breadth of the process will be suffused by steps through which a coherent 
geometry unfolds. In the case of buildings the fountain of geometrical order
comes, above all, from building /structure/ (columns, walls, beams, vaults, and
so forth), specifically from the aperiodic, tartan like grids which form the 
abstract underpining of the building structure.

In this chapter: how it is ultimately the powerful formation of this structural
core that provides a living building with its geometrical substratum.

** Reasons for brutal geometric order to evolve
There are 2 questions:
- why the appearance of distinct levels of mass and scale must happen inevitably
  in a living process as one develops the building structure
- why the appearance of the geometry as it ensues in the building, may be 
  described as almost brutal.

For the first question:
- we are at first find likely to find an order which is "informal", not too 
  rigid, rather soft and harmonious and it fits itself to a landscape, or to a
  valley, or to a street, or to the seeming disarray of neighboring buildings.
  This /softness/ is what characterizes the "old" way.
- But as we try to create this kind of soft order, there comes a time, 
  inevitably when we have to /impose/. We have to create a geometry that comes
  almost from the space itself, from the discipline of rectangles, and from the
  discipline of equal or nearly equal structural bays
--> it comes from the need for the internal geometrical coherence of the 
building, not from the surroundings. Of course, as we introduce this formal 
geometry, work it, care for it, we do our best to make it harmonious, we tame it
we introduce necessary irregularities to make it fit the surroundings as well as
possible.

For the second question:
- There is at the kernel of the whole process, an inevitable moment of truth 
  which really is rather brutal, the moment when geometry, coming about for its 
  own sake, imposes a discipline of its own that /must/ be introduced.
- imposition of a discipline is undeniably a brutal act. Yet it is from this
  moment of brutality, that real order must come.

--> It is this injection of definite, strong, geometrical order that allows the
profound depth of the made thing.

** The aperiodic grid
Another way to express brutality: There comes a time in the evolution of a 
building form when we must forget the context, the plan, even turn our back on
these things, and /focus only on the pure beauty of the structural order/, the
building as a thing of beauty in itself.

This is focused on beauty. It is brutal, only because, to do it, we must forget
our responsibilities and the subtleties of site and function, and enter the play
of pure forms with as much emphasis on feeling, art, and structure alone as we
can.


** What is really happening in such a case
What is the essence of this process for buildings? How is it related to the
"brutal" aspects of process I have been describing? How is it related to the 
repetition of the fundamental process that is required by all living processes?
- The volumn is already fixed.
- we have a rough idea of the way space is to be disposed inside this volume. In
  broad terms, we have divided the thing up into areas and positions, possibly
  including exterior areas or spaces
- crucial step when orderly geometry of structured is introduced. We apply, to
  this configuration of roughly conceived spaces, a special kind of sharpening
  process: we use it to construct the simplest aperiodic grid consistent with
  the harmony and variety of the building plan.

** Outward simplicity of form and packing of form
In some cases the "brutal" effect of geometry takes rather simple character. It
sometimes is more a matter of pure geometry.
The principle is: a rigid and definite geometry is introduced in a nearly brutal
manner, but is then treated, bent, filled, and modified, so that its coherent
existence, while being adapted to rooms, circumstances, needs and land, is
nevertheless able to happen beautifully within a visible and satisfying order.

** A Generative process for middle-range order in the building structure
middle-range order: the existence of entities - centers - at the scale of rooms,
bays, portions of a building.
It is the use of generating process and the use of the aperiodic grid which 
produces these middle-sized centers.
How this process is related to the fundamental process and to the idea of living
process
  - when we construct an aperiodic grid, the critical issue is the alternation
    of narrow grid bands with larger grid bands: allows for the creation of 
    boundaries and levels of scale
  - within this grid, it is certainly obvious that STRONG CENTERS, LOCAL 
    SYMMETRIES, GOOD SHAPE, LEVELS OF SCALE play a huge part
  - the existence of these halfway, middle-range centers in a living structure
    sheds a great deal of light on the unfolding process.
  - the effort is to make each "thing" positive.

** What seems like an imposition of geometry is necessary as a part of every living process
This formal creation of geometry really apply to other living processes
  - the formation of a community
  - creation of a human group
  - brushwork of a delicate painting
  - construction of a song played by a flute
brutal and too-decisive though it may seem is the process by which the guts of a
thing, its valuable force, is made

* Form language and style
(How can human beings implement a geometrical differentiating process 
successfully)

** The format of our art
It is a fundamental issue that belongs square in the middle of the analysis of
living structure as a product of society
Start from the fact, obvious enough, that we do not start each new design from
scratch. We learn over years the ingredients that make a building good.
At any given period of history, in any particular society, there are a certain
number of schemata which provide rules of thumb for designing and constructing
buildings. The form-language is the combinatory system of these schemata (social,
technological, geometric, stylistic, etc). 
Form-language the repository of style (p432)
We shall only be able to reproduce versions and combinations of what can be
"reached" by that form language. (p433)
Reasons:
  - the nature of human cognition is such that people will, in any case, use
    schemata as the basis of their building operations
  - It is, in essense, the shared form language of society.

It is reasonable to ask, therefore, what a modern form language would need to be
like, if it were to help us reach the goal of living process in our highly 
modern and technically sophisticated society. (p433)
If we want a living world, and we want one which is created and generated by 
living process, it is imperative that the form languages we use, and the form
languages available to us, help us and support us in this task.

Unless we have a form language which supports the necessities of living structure,
then living structure is simply out of our reach. If a society has inadequate
style, inadequate shapes and forms, then no matter how hard the builders and 
architects try, the environment they create will not be, /and cannot be/ a 
living structure

*Most vital targets of Alexander's search*: in order to make living process 
possible, we must take at least first steps towards a new form language - in 
effects 

The problem: *How is such a language to be discovered*

** Historically, what kind of thing did a form language do?
What a form language is? and what it can do?
The pattern languages and sequences in use in traditional societies, nearly 
always specified form, shape, volume, material, style, ornament. They embodied a
coherent geometric, visual, physical style, so that now, long afterwards, the 
architecture of each given place and time, is still recognizable as part of the
geometric living unity which was created by that culture.

the creation of living structure:
  - the emergence of living process
  - ppl shape things, planning, making the building through the sequence of form 
    language, share some coherence of style and geometric substance.

** The modern theory of language
The concept of "language" was given by several mathematicians, for the case of
natural language by Noam Chomsky who coined the phrase /transformation grammar/.
The basic idea:
  - a string creating system was defined.
  - the starting point was usually a null sentence consisting of a single 
    character, or word, or the null string.
  - the language provides a series of rule which allowed certain kinds of 
    transformations which would elaborate a given string.

There is the enormous challenge of making such a language concrete, and culture
specific, while not hampering it with traditional or historical reference.

** Building a form-language from theory
a form language able to produce life must be a system of transformations which
allows such living centers to be created, one by one, or a few at a time, 
gradually creating a profusion of coordinated and interdependent living centers,
each well-related and supportive to the larger wholes around it. (p444)

** The form of future buildings sketches to illustrate the output from a new form language
the vital role of /unfolding/ - the process by which form is created through 
differentation - and to see clearly how this comes about, what kinds of elements
and local symmetries will typically be generated by unfolding

This statement is highly abstract, highly general, and not oriented to history
The step-by-step evolution of living centers, in a progressive differentiating
process, is /necessary/ to the adaption process. It is not a cultural decision, 
not an emotional decision, but a biological necessity - an essential part of the
adaptation of a complex system.
